// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: defenitions/users_v1.proto

package rpcusers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_defenitions_users_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_defenitions_users_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_defenitions_users_v1_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_defenitions_users_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_defenitions_users_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_defenitions_users_v1_proto_rawDescGZIP(), []int{1}
}

type UpdateUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsernameRequest) Reset() {
	*x = UpdateUsernameRequest{}
	mi := &file_defenitions_users_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsernameRequest) ProtoMessage() {}

func (x *UpdateUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_defenitions_users_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsernameRequest.ProtoReflect.Descriptor instead.
func (*UpdateUsernameRequest) Descriptor() ([]byte, []int) {
	return file_defenitions_users_v1_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUsernameRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UpdateUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsernameResponse) Reset() {
	*x = UpdateUsernameResponse{}
	mi := &file_defenitions_users_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsernameResponse) ProtoMessage() {}

func (x *UpdateUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_defenitions_users_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsernameResponse.ProtoReflect.Descriptor instead.
func (*UpdateUsernameResponse) Descriptor() ([]byte, []int) {
	return file_defenitions_users_v1_proto_rawDescGZIP(), []int{3}
}

type CheckUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUsernameRequest) Reset() {
	*x = CheckUsernameRequest{}
	mi := &file_defenitions_users_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUsernameRequest) ProtoMessage() {}

func (x *CheckUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_defenitions_users_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUsernameRequest.ProtoReflect.Descriptor instead.
func (*CheckUsernameRequest) Descriptor() ([]byte, []int) {
	return file_defenitions_users_v1_proto_rawDescGZIP(), []int{4}
}

func (x *CheckUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type CheckUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUsernameResponse) Reset() {
	*x = CheckUsernameResponse{}
	mi := &file_defenitions_users_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUsernameResponse) ProtoMessage() {}

func (x *CheckUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_defenitions_users_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUsernameResponse.ProtoReflect.Descriptor instead.
func (*CheckUsernameResponse) Descriptor() ([]byte, []int) {
	return file_defenitions_users_v1_proto_rawDescGZIP(), []int{5}
}

func (x *CheckUsernameResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_defenitions_users_v1_proto protoreflect.FileDescriptor

const file_defenitions_users_v1_proto_rawDesc = "" +
	"\n" +
	"\x1adefenitions/users_v1.proto\x12\vsm.users.v1\"\\\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\x12\n" +
	"\x10RegisterResponse\"L\n" +
	"\x15UpdateUsernameRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\x18\n" +
	"\x16UpdateUsernameResponse\"2\n" +
	"\x14CheckUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"/\n" +
	"\x15CheckUsernameResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2\x8a\x02\n" +
	"\fUsersService\x12G\n" +
	"\bRegister\x12\x1c.sm.users.v1.RegisterRequest\x1a\x1d.sm.users.v1.RegisterResponse\x12Y\n" +
	"\x0eUpdateUsername\x12\".sm.users.v1.UpdateUsernameRequest\x1a#.sm.users.v1.UpdateUsernameResponse\x12V\n" +
	"\rCheckUsername\x12!.sm.users.v1.CheckUsernameRequest\x1a\".sm.users.v1.CheckUsernameResponseB%Z\x14go/rpcusers;rpcusers\xaa\x02\fSM.Rpc.Usersb\x06proto3"

var (
	file_defenitions_users_v1_proto_rawDescOnce sync.Once
	file_defenitions_users_v1_proto_rawDescData []byte
)

func file_defenitions_users_v1_proto_rawDescGZIP() []byte {
	file_defenitions_users_v1_proto_rawDescOnce.Do(func() {
		file_defenitions_users_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_defenitions_users_v1_proto_rawDesc), len(file_defenitions_users_v1_proto_rawDesc)))
	})
	return file_defenitions_users_v1_proto_rawDescData
}

var file_defenitions_users_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_defenitions_users_v1_proto_goTypes = []any{
	(*RegisterRequest)(nil),        // 0: sm.users.v1.RegisterRequest
	(*RegisterResponse)(nil),       // 1: sm.users.v1.RegisterResponse
	(*UpdateUsernameRequest)(nil),  // 2: sm.users.v1.UpdateUsernameRequest
	(*UpdateUsernameResponse)(nil), // 3: sm.users.v1.UpdateUsernameResponse
	(*CheckUsernameRequest)(nil),   // 4: sm.users.v1.CheckUsernameRequest
	(*CheckUsernameResponse)(nil),  // 5: sm.users.v1.CheckUsernameResponse
}
var file_defenitions_users_v1_proto_depIdxs = []int32{
	0, // 0: sm.users.v1.UsersService.Register:input_type -> sm.users.v1.RegisterRequest
	2, // 1: sm.users.v1.UsersService.UpdateUsername:input_type -> sm.users.v1.UpdateUsernameRequest
	4, // 2: sm.users.v1.UsersService.CheckUsername:input_type -> sm.users.v1.CheckUsernameRequest
	1, // 3: sm.users.v1.UsersService.Register:output_type -> sm.users.v1.RegisterResponse
	3, // 4: sm.users.v1.UsersService.UpdateUsername:output_type -> sm.users.v1.UpdateUsernameResponse
	5, // 5: sm.users.v1.UsersService.CheckUsername:output_type -> sm.users.v1.CheckUsernameResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_defenitions_users_v1_proto_init() }
func file_defenitions_users_v1_proto_init() {
	if File_defenitions_users_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_defenitions_users_v1_proto_rawDesc), len(file_defenitions_users_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_defenitions_users_v1_proto_goTypes,
		DependencyIndexes: file_defenitions_users_v1_proto_depIdxs,
		MessageInfos:      file_defenitions_users_v1_proto_msgTypes,
	}.Build()
	File_defenitions_users_v1_proto = out.File
	file_defenitions_users_v1_proto_goTypes = nil
	file_defenitions_users_v1_proto_depIdxs = nil
}
